# Generated by Django 3.2.4 on 2021-06-28 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_email'),
        ('quiz', '0006_auto_20210624_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='student.dept'),
        ),
        migrations.AddField(
            model_name='course',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='student.position'),
        ),
    ]
