# Generated by Django 3.2.4 on 2021-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_email'),
        ('quiz', '0007_auto_20210628_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dept',
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ManyToManyField(to='student.Dept'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='position',
        ),
        migrations.AddField(
            model_name='course',
            name='position',
            field=models.ManyToManyField(to='student.Position'),
        ),
    ]
