# Generated by Django 3.2.4 on 2021-07-07 01:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210706_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Вариант 1', 'Option1'), ('Вариант 2', 'Option2'), ('Вариант 3', 'Option3'), ('Вариант 4', 'Option4'), ('Вариант 5', 'Option5'), ('Рисунок 1', 'Picture1'), ('Рисунок 2', 'Picture2'), ('Рисунок 3', 'Picture3'), ('Рисунок 4', 'Picture4'), ('Рисунок 5', 'Picture5'), ('Вводимый ответ', 'Entry_answer')], default=False, max_length=200),
        ),
    ]
