# Generated by Django 3.2.4 on 2021-06-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210628_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='student.dept'),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='student.position'),
        ),
    ]
